add_newline = false

format = """
╭[](#769ff0)$time[ | ](bg:#769ff0)$username[$git_branch](bg:#769ff0 fg:black) $c $nodejs $rust $java
╰──$character"""
right_format = "$cmd_duration"

[character]
success_symbol = "[>]()"
error_symbol = "[1](bold red)"

[directory.substitutions]
"~" = "Home"

[c]
symbol = ""
style = "bg:#769ff0"
format = "[[](#769ff0)[$symbol](bg:#769ff0 fg:white)[](fg:#769ff0 bg:white)$version](fg:black bg:white)[](white)"

[username]
disabled = false
style_root = "bg:#769ff0"
style_user = "bg:#769ff0"
format = "[$user]($style)[](fg:#769ff0 bg:#394260)"
show_always = true

[hostname]
disabled = false
format = "$hostname"
ssh_only = false

[cmd_duration]
disabled = false
format = "[](white)[took $duration](bg:white fg:black)[](white)"

[time]
disabled = false
use_12hr = true
style = "bg:#769ff0"
format = "[$time]($style)"

[localip]
ssh_only = false
disabled = false
format = "on [$localipv4](bold red)"

[git_branch]
symbol = ""
style = "bg:#394260"
format = '[[ ](fg:#769ff0 bg:#394260)[$symbol $branch ](fg:#769ff0 bg:#394260)]($style)[](#394260)'

[nodejs]
symbol = ""
style = "bg:#212736"
format = "[[](#769ff0)[$symbol](bg:#769ff0 fg:white)[](fg:#769ff0 bg:white)$version](fg:black bg:white)[](white)"

[rust]
format = "[[](#769ff0)[$symbol](bg:#769ff0 fg:white)[](fg:#769ff0 bg:white)$version](fg:black bg:white)[](white)"

[java]
format = "[[](#769ff0)[$symbol](bg:#769ff0 fg:white)[](fg:#769ff0 bg:white)$version](fg:black bg:white)[](white)"
